const { open, waitReady, ROOT } = require('./harness.cjs');
const path = require('path');
(async () => {
  const { browser, page, logs } = await open({ preset: 'LOW', viewport: { width: 960, height: 540 } });
  let seen = 0;
  const newLogs = () => { const l = logs.slice(seen).filter((x) => !x.startsWith('[log]') && !x.includes('GPU stall') && !x.includes('Automatic fallback')); seen = logs.length; return l; };
  const ev = async (name, fn, arg) => {
    try { const r = await Promise.race([page.evaluate(fn, arg), new Promise((_, rej) => setTimeout(() => rej(new Error('eval timeout')), 120000))]); console.log(`✓ ${name}:`, typeof r === 'string' ? r : JSON.stringify(r)); }
    catch (e) { console.log(`✗ ${name}: ${e.message.split('\n')[0]}`); }
    const l = newLogs(); if (l.length) console.log('   logs:\n   ' + l.join('\n   ').slice(0, 2500));
  };
  try {
    await waitReady(page);
    await page.evaluate(() => window.__tvs.sys.Game.start(null, { name: 'Sys' }));
    await page.waitForTimeout(1500); newLogs();
    await ev('money + tractor + implements', () => { const g = window.__tvs, s = g.sys; g.S.money = 5e7; s.UI.buyVehicle('tractor35'); for (const id of ['plough', 'cultivator', 'rotavator', 'seeddrill', 'sprayer', 'spreader', 'trailer', 'tanker']) g.S.implements.push(id); s.UI.close(); return s.Vehicles.player.map((v) => v.type + '@' + v.x.toFixed(0) + ',' + v.z.toFixed(0)); });
    await ev('interact near bullocks', () => { const s = window.__tvs.sys; const v = s.Vehicles.player.find((q) => q.type === 'bullock'); s.Player.x = v.x + 2; s.Player.z = v.z; s.Interact.update(); return s.Interact.current.map((o) => o.id + ':' + o.label()); });
    await ev('tractor rotavate F1', () => { const s = window.__tvs.sys; const f = s.Fields.byId.F1; const v = s.Vehicles.player.find((q) => q.type === 'tractor35'); v.attach('rotavator'); v.x = f.x0 + 2; v.z = f.z0 - 2; v.yaw = 0; v.place(); s.Player.enterVehicle(v); v.lowered = true; const before = f.countMin(2); let steps = 0; for (let lane = 0; lane < 4; lane++) { v.x = f.x0 + 1.5 + lane * 2.2; v.z = f.z0 - 1; v.yaw = 0; v.speed = 0; for (let i = 0; i < 260 && v.z < f.z1 + 3; i++) { v.update(1 / 20, { throttle: 0.7, steer: 0, brake: false }); steps++; } } const after = f.countMin(2); s.Player.exitVehicle(true); return { before, after, steps, fuel: v.fuel.toFixed(1), cond: v.cond.toFixed(1) }; });
    await ev('seed drill paddy', () => { const s = window.__tvs.sys; const f = s.Fields.byId.F1; s.Inv.add('seed_maize', 2); const v = s.Vehicles.player.find((q) => q.type === 'tractor35'); v.attach('seeddrill'); v.sowCrop = 'maize'; s.Player.enterVehicle(v); v.lowered = true; for (let lane = 0; lane < 4; lane++) { v.x = f.x0 + 1.5 + lane * 2.6; v.z = f.z0 - 1; v.yaw = 0; v.speed = 0; for (let i = 0; i < 260 && v.z < f.z1 + 3; i++) v.update(1 / 20, { throttle: 0.7, steer: 0, brake: false }); } s.Player.exitVehicle(true); return { sown: f.count(3), crop: f.crop, seeds: s.Inv.count('seed_maize').toFixed(2) }; });
    await ev('harvester service on ready field', () => { const s = window.__tvs.sys; const f = s.Fields.byId.F1; for (let i = 0; i < f.n; i++) f.tiles[i] = 3; f.sownTiles = f.n; f.crop = 'maize'; f.growth = 1; f.health = 90; f.cropDirty = true; s.Services.harvestService(f); return { svc: (s.Services.svcList || []).length, job: !!(s.Services.svcList || [])[0]?.job }; });
    await ev('run harvester job 120s', () => { const s = window.__tvs.sys; const f = s.Fields.byId.F1; const v = s.Services.svcList[0]; const trace = []; for (let i = 0; i < 2400; i++) { s.Services.updateSvc(1 / 20); if (i % 400 === 0) trace.push(`${v.job ? v.job.phase + ':' + v.job.i + '/' + v.job.pts.length : 'done'} @${v.x.toFixed(0)},${v.z.toFixed(0)} sp=${v.speed.toFixed(1)} left=${f.count(3)}`); } return { trace, left: f.count(3), heap: f.heap && f.heap.qty.toFixed(1) }; });
    await ev('driver worker with rotavator', () => { const g = window.__tvs, s = g.sys; const f = s.Fields.byId.F1; f.heap = null; f.heapDirty = true; for (let i = 0; i < f.n; i++) f.tiles[i] = 0; f.crop = null; f.sownTiles = 0; f.allDirty = true; f.plannedCrop = 'maize'; s.Inv.add('seed_maize', 3); g.S.time.min = Math.floor(g.S.time.min / 1440) * 1440 + 9 * 60; s.Workers.hire('driver'); const n = s.Workers.list[s.Workers.list.length - 1]; const trace = []; for (let i = 0; i < 3600; i++) { s.Workers.update(1 / 20); s.Vehicles.update(1 / 20); if (i % 600 === 0) trace.push(`${n.job ? n.job.op + ':' + n.job.phase + ':' + n.job.i + '/' + n.job.pts.length : 'none'} t0=${f.count(0)} t2=${f.count(2)} t3=${f.count(3)}`); } return trace; });
    await ev('storage unload/load', () => { const s = window.__tvs.sys; const f = s.Fields.byId.F1; const v = s.Vehicles.player.find((q) => q.type === 'tractor35'); v.attach('trailer'); if (f.heap) s.Services.loadHeap(v, f); const load = v.cargoQty; s.Player.enterVehicle(v); s.UI.storageMenu(v); const btns = [...document.querySelectorAll('#modal button.btn')].map((b) => b.textContent); const un = [...document.querySelectorAll('#modal button.btn')].find((b) => /Unload|దించ/.test(b.textContent)); if (un) un.click(); s.UI.close(); s.Player.exitVehicle(true); return { load: load.toFixed(1), btns, storage: window.__tvs.S.storage.map((e) => e.crop + ':' + e.qty.toFixed(1)) }; });
    await ev('msp sell flow', () => { const s = window.__tvs.sys; const v = s.Vehicles.player.find((q) => q.type === 'tractor35'); s.UI.loadFromStorage(v, 'maize', 5); s.UI.mspMenu(v); const txt = document.getElementById('modal').innerText.slice(0, 240); const b = [...document.querySelectorAll('#modal button.btn')].find((x) => /Sell|అమ్మ|Register|నమోదు/.test(x.textContent)); if (b) b.click(); s.UI.close(); return { txt, clicked: b && b.textContent, pending: window.__tvs.S.pending.length, cargo: v.cargoQty.toFixed(1) }; });
    await ev('bus to town', () => { const s = window.__tvs.sys; s.Services.busTravel('town'); return 'queued'; });
    await page.waitForTimeout(1500);
    await ev('after bus', () => { const s = window.__tvs.sys; return { P: [s.Player.x.toFixed(0), s.Player.z.toFixed(0)], clock: s.Time.fmtClock() }; });
    await ev('build dairy + polyhouse + garage', () => { const g = window.__tvs, s = g.sys; for (const id of ['dairyShed', 'greenhouse', 'garage', 'warehouse', 'coldStorage', 'quarters', 'farmPond', 'solarPump']) s.Farm.buyUpgrade(id); s.Sim.advance(36 * 60); return { up: Object.keys(g.S.up), dairy: g.S.dairy.n, gh: s.Fields.byId.GH.owner, milk: g.S.stats.milk }; });
    await ev('village projects all', () => { const g = window.__tvs, s = g.sys; for (const id in { roads: 1, tank: 1, shops: 1, school: 1, health: 1, irrigation: 1, godown: 1, market: 1 }) s.Village.start(id); s.Sim.advance(42 * 60); return { village: g.S.village, rank: g.S.rank }; });
    await ev('house upgrades to max', () => { const g = window.__tvs, s = g.sys; for (let i = 0; i < 4; i++) { s.Farm.upgradeHouse(); s.Sim.advance(61 * 60); } return { house: g.S.houseLevel }; });
    await ev('village bore mission + repair', () => { const g = window.__tvs, s = g.sys; s.Missions.add({ tpl: 'repairBore', title: { en: 'Fix bore', te: 'బోరు' }, desc: { en: '', te: '' }, reward: 1000, target: 1, mark: 'vbore' }); s.Inv.add('pumppart', 1); s.Services.repairVillageBorewell(); return { fixed: g.S.flags.boreFixed, active: g.S.missions.active.map((m) => m.tpl) }; });
    await ev('pest outbreak event', () => { const g = window.__tvs, s = g.sys; const f = s.Fields.byId.F1; for (let i = 0; i < f.n; i++) f.tiles[i] = 3; f.sownTiles = f.n; f.crop = 'cotton'; f.growth = 0.4; f.outbreak = false; s.Bus.emit('pestOutbreak', { field: f }); return g.S.missions.active.map((m) => m.tpl); });
    await ev('drought event', () => { const g = window.__tvs, s = g.sys; s.Bus.emit('drought', {}); return g.S.missions.active.map((m) => m.tpl); });
    await ev('hire workers + driver', () => { const g = window.__tvs, s = g.sys; s.Workers.hire('farmhand'); s.Workers.hire('farmhand'); s.Workers.hire('driver'); s.Workers.hire('daily'); for (let i = 0; i < 60; i++) s.Workers.update(0.5); return { workers: g.S.workers.map((w) => w.type), npc: s.Workers.list.length }; });
    await ev('rank check', () => { const g = window.__tvs, s = g.sys; g.S.stats.cropIncome = 3.5e7; for (const f of s.Fields.list.filter((q) => q.avail === 'sale' || q.avail === 'both').slice(0, 14)) s.Farm.buyField(f); s.Progress.check(); return { rank: g.S.rank, owned: s.Farm.ownedAcres().toFixed(1), villages: s.Farm.villages() }; });
    await ev('photo + map waypoint', () => { const s = window.__tvs.sys; s.UI.photo(); s.UI.photo(); s.UI.map(); const cv = document.querySelector('#modal canvas'); const r = cv.getBoundingClientRect(); const o = { clientX: r.left + r.width * 0.6, clientY: r.top + r.height * 0.4, bubbles: true, pointerId: 7 }; cv.dispatchEvent(new PointerEvent('pointerdown', o)); cv.dispatchEvent(new PointerEvent('pointerup', o)); s.UI.close(); return window.__tvs.S.waypoint; });
    await ev('telugu UI', () => { const s = window.__tvs.sys; s.Settings.v.lang = 'te'; s.UI.applyLang(); s.UI.office('profile'); const t = document.getElementById('modal').innerText.slice(0, 160); s.UI.close(); s.UI.dirty = true; s.UI.update(1); return t + ' | ' + document.getElementById('date').textContent; });
    await page.waitForTimeout(2500);
    await page.screenshot({ path: path.join(ROOT, 'shots/s_telugu.png'), timeout: 120000 });
    await ev('preset switching', () => { const s = window.__tvs.sys; const out = []; for (const p of ['MEDIUM', 'HIGH', 'ULTRA', 'CINEMATIC', 'LOW']) { s.Game.setPreset(p); out.push(window.__tvs.preset.id); } return out; });
    await ev('save size', () => { const s = window.__tvs.sys; s.SaveSys.save(true); return (localStorage.getItem('tvs_save_v1') || '').length; });
  } catch (e) { console.log('TEST ERROR', e.message); }
  const l = newLogs(); if (l.length) console.log('remaining logs:\n' + l.join('\n').slice(0, 3000));
  await browser.close();
})();
